// Embeds widget/dist/index.html into src/mcp/widget-html.generated.ts (committed; CI fails on a diff).
// WIDGET_VERSION = first 8 hex chars of sha256(html). Output is deterministic for identical input.
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { isMain, REPO_ROOT } from "./lib/env-files";

function main() {
  const html = readFileSync(resolve(REPO_ROOT, "widget/dist/index.html"), "utf8");
  const version = createHash("sha256").update(html).digest("hex").slice(0, 8);
  const out = resolve(REPO_ROOT, "src/mcp/widget-html.generated.ts");
  mkdirSync(dirname(out), { recursive: true });
  const file =
    "// GENERATED by scripts/embed-widget.ts from widget/. Do not edit; run `pnpm widget:build`.\n" +
    `export const WIDGET_HTML = ${JSON.stringify(html)};\n` +
    `export const WIDGET_VERSION = ${JSON.stringify(version)};\n`;
  writeFileSync(out, file);
  console.log(`widget: ${(html.length / 1024).toFixed(1)} KB, version ${version}`);
}

if (isMain("scripts/embed-widget.ts")) main();
